services:
  app:
    restart: "no"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: .env
    ports:
      - "${APACHE_UNSECURE_PORT}:80"
    volumes:
      - ../app:/var/www/html
      - vendor_data:/var/www/html/vendor
      - ./logs:/var/log/app
  mariadb:
    image: mariadb:10.6
    restart: "no"
    env_file: .env
    ports:
      - "${MARIADB_HOST_PORT}:3306"
    volumes:
      - sans_data:/var/lib/mysql
volumes:
  sans_data:
    name: ${COMPOSE_PROJECT_NAME}_data
  vendor_data:
    name: ${COMPOSE_PROJECT_NAME}_vendor
